# Generated by Django 4.2.4 on 2023-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='apartment_images/%Y/%m/%d/'),
        ),
    ]
